using System;
using System.Linq;
using System.Threading.Tasks;
using Flow.Grains.Events;
using Flow.Grains.Expressions;
using Flow.Grains.Infrastructure.Extensions;
using Flow.Grains.Interfaces.Model;
using Flow.Grains.Plan.CmmnElement;
using Microsoft.Extensions.Logging;
using Orleans.Streams;

namespace Flow.Grains.Plan.Sentry
{
    /// <summary>
    /// A Sentry may consist of two parts:
    /// • Zero or more OnParts. An OnPart specifies the event that serves as trigger. When the event is catched, the OnPart is
    ///   said to “occur.”
    /// • Zero or one IfPart. The IfPart specifies a condition, as Expression that evaluates over the CaseFile. If all
    ///   OnParts of a Sentry have occurred and its IfPart (if existent) evaluates to TRUE, the Sentry is said to be
    ///   “satisfied.”
    /// 
    /// A Sentry's OnPart is satisfied when one of the following conditions is satisfied:
    ///     • For a PlanItemOnPart, its Sentry referred by sentryRef has occurred.
    ///     • For a PlanItemOnPart or CaseFileItemOnPart, its sourceRef transitions into the transition described by the
    ///       standardEvent (PlanItemTransition, or CaseFileItemTransition).
    /// A Sentry is satisfied when one of the following conditions is satisfied:
    ///     • All of the OnParts are satisfied AND the IfPart condition evaluates to TRUE.
    ///     • All of the OnParts are satisfied AND there is no IfPart.
    ///     • The IfPart condition evaluates to TRUE AND there are no OnParts.
    /// 
    /// Entry criterion sentries are considered ready for evaluation while the task, stage, or milestone is in Available state. Exit
    /// criterion sentries are considered ready for evaluation while the CasePlanModel, State, or Task is in Active state.
    /// Sentries are evaluated when events arrive to the system or when events are generated by the system. A single event may
    /// satisfy multiple sentries. Sentries with no OnPart must have an IfPart, and that IfPart will be evaluated for all
    /// CaseFileItem events because IfPart expressions are based on CaseFileItem properties.
    /// </summary>
    public class SentryGrain :
        CmmnElementGrain<SentryStore, Interfaces.Model.Sentry>,
        ISentryGrain
    {
        public SentryGrain(ILogger<SentryGrain> logger) :
            base(logger)
        {
        }

        public override async Task OnActivateAsync()
        {
            await base.OnActivateAsync();

            if (TentativeState.IsDefined)
            {
                await SubscribeToOnPartTransitions(StreamFlags.Resume);
            }
        }

        public override async Task Define(Guid caseDefinitionId, Interfaces.Model.Sentry definition)
        {
            await base.Define(caseDefinitionId, definition);
            await SubscribeToOnPartTransitions(StreamFlags.Create);
        }

        #region Streams

        private Task SubscribeToOnPartTransitions(StreamFlags flags) =>
            Task.WhenAll(Definition.OnParts
                .Select(onPart =>
                {
                    switch (onPart)
                    {
                        case PlanItemOnPart planItemOnPart:
                        {
                            return SubscribeTo<PlanItemTransitionedEvent>(
                                planItemOnPart.SourceRef,
                                HandlePlanItemTransitioned,
                                flags);
                        }
                        case CaseFileItemOnPart caseFileItemOnPart:
                        {
                            return SubscribeTo<CaseFileItemTransitionedEvent>(
                                caseFileItemOnPart.SourceRef,
                                HandleCaseFileItemTransitioned,
                                flags);
                        }
                        default:
                        {
                            return Task.CompletedTask;
                        }
                    }
                }));

        private async Task HandlePlanItemTransitioned(PlanItemTransitionedEvent @event, StreamSequenceToken token = null)
        {
            // ignore events that are not in this sentry's hierarchy
            if (!@event.SourceScope.StartsWith(_scope)) return;

            var onPart = Definition.PlanItemOnParts
                .SingleOrDefault(x =>
                    x.StandardEvent == @event.StandardEvent &&
                    (string.IsNullOrWhiteSpace(x.SourceRef) || x.SourceRef.Equals(@event.SourceId) &&
                    (string.IsNullOrWhiteSpace(x.ExitCriterionRef) || x.ExitCriterionRef.Equals(@event.ExitCriterionRef))));

            // no matching onPart
            if (onPart == null) return;

            await HandleOnPartOccurred(onPart, @event.SourceScope, @event.SourceId, @event.StandardEvent);
        }

        private async Task HandleCaseFileItemTransitioned(CaseFileItemTransitionedEvent @event, StreamSequenceToken token = null)
        {
            var onPart = Definition.CaseFileItemOnParts
                .SingleOrDefault(x =>
                    x.StandardEvent == @event.StandardEvent &&
                    (string.IsNullOrWhiteSpace(x.SourceRef) || x.SourceRef.Equals(@event.SourceId)));

            // no matching onPart
            if (onPart == null) return;

            await HandleOnPartOccurred(onPart, @event.SourceScope, @event.SourceId, @event.StandardEvent);
        }

        private async Task HandleOnPartOccurred(OnPart onPart, string sourceScope, string sourceId, object standardEvent)
        {
            LogWithContext(logger => logger.LogInformation(
                "{ElementType} {ElementScope}.{ElementId}: {OnPartType} {OnPartId} occurred via {EventSourceScope}.{EventSourceId} transition {StandardEvent}",
                Definition.GetType().Name,
                _scope,
                _id,
                onPart.GetType().Name,
                onPart.Id,
                sourceScope,
                sourceId,
                standardEvent));

            RaiseEvent(new OnPartOccurred
            {
                OnPart = onPart
            });

            if (TentativeState.OccurredOnParts.Count() == Definition.OnParts.Count && await EvaluateIfPart())
            {
                RaiseEvent(new Satisfied());
            }

            await ConfirmEvents();

            if (!State.Satisfied) return;

            LogWithContext(logger => logger.LogInformation(
                "{ElementType} {ElementScope}.{ElementId}: sentry satisfied, notifying subscribers",
                Definition.GetType().Name,
                _scope,
                _id));

            await Publish(new SentrySatisfiedEvent(_scope, Definition.Id, true));
        }

        #endregion Streams

        private async Task<bool> EvaluateIfPart()
        {
            if (Definition.IfPart?.Condition == null) return true;

            var result = await GrainFactory.GetGrain<IExpressionGrain>(_caseInstanceId)
                .ExecuteAsBool(Definition.IfPart.ContextRef, Definition.IfPart.Condition);

            if (result.IsError) return false;

            // TODO: how do we handle a fault in a sentry?  publish event to fault the parent stage?

            return result.Value;
        }
    }
}
