using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;
using System.Xml.Serialization;

namespace Wayfinder.Grains.Interfaces.Model.Interchange
{
    // Spec §9.3.1 (Document Structure): "A domain-specific set of Case model elements is
    // interchanged in one or more CMMN files. The root element of each file MUST be
    // <cmmn:definitions>." Shared by every hand-authored type in this folder and by
    // Wayfinder.Grains/Interchange/CmmnXmlSerializer.cs, so the namespace literal appears exactly
    // once outside the XSD-generated Spec.CMMN.MODEL.cs (which, being generated, repeats it
    // per-attribute by construction - see that file for the precedent this folder follows).
    public static class CmmnXml
    {
        public const string Namespace = "http://www.omg.org/spec/CMMN/20151109/MODEL";
    }

    // tDefinitions (spec §5.1.2, §9.3.1) - "the outermost containing object for all
    // CMMNElements. It defines the scope of visibility and the namespace for all contained
    // elements. The interchange of CMMN files will always be through one or more Definitions."
    //
    // NOT XSD-generated, unlike everything else in Model/: Spec.CMMN.MODEL.cs (the actual
    // generator output - see its <auto-generated> header) stops at the Case-model level and has
    // no root wrapper type. Every symbol in this codebase that consumes a model
    // (ICaseDefinitionGrain.Define(Case), every test that builds a case by hand) works directly
    // with `Case`; nothing before this work item ever needed a `Definitions` to hold one.
    // Authored here by hand, in the same XmlSchemaClassGenerator attribute idiom as the rest of
    // Model/, so it slots into System.Xml.Serialization.XmlSerializer identically to a generated
    // type and needs no special-casing from CmmnXmlSerializer.
    //
    // Content model transcribed from the AUTHORITATIVE OMG schema, not guessed from prose:
    // CMMN11.xsd (http://www.omg.org/spec/CMMN/20151109/CMMN11.xsd) declares tDefinitions'
    // sequence as import*, caseFileItemDefinition*, case*, process*, decision*,
    // extensionElements?, relationship*, artifact*, cmmndi:CMMNDI? - the element properties below
    // are declared in exactly that order (this model carries no XmlElement Order hints anywhere,
    // so import is order-insensitive by name; declaration order only shapes EXPORT output, and
    // matching the XSD sequence keeps exported documents schema-valid at the root). tDefinitions
    // also carries xsd:anyAttribute (##other, lax) - mapped to AnyAttributes below so extension
    // attributes on the root round-trip instead of silently dropping. The one deliberate
    // omission is cmmndi:CMMNDI - diagram interchange is out of this MVP's scope (see this work
    // item's report); a DI section in an imported file is skipped, not round-tripped.
    //
    // artifact* accepts three element names because CMMN11CaseModel.xsd declares
    // <xsd:element name="artifact" type="tArtifact"/> (non-abstract) with association and
    // textAnnotation as its substitutionGroup members - the same substitution-group-to-
    // [XmlElement-per-name] translation the generator itself used for Stage.PlanItemDefinitions.
    [XmlType("tDefinitions", Namespace = CmmnXml.Namespace)]
    [XmlRoot("definitions", Namespace = CmmnXml.Namespace)]
    public class Definitions
    {
        public Definitions()
        {
            Imports = new List<Import>();
            CaseFileItemDefinitions = new List<CaseFileItemDefinition>();
            Cases = new List<Case>();
            Processes = new List<Process>();
            Decisions = new List<Decision>();
            Relationships = new List<Relationship>();
            Artifacts = new List<Artifact>();
            _anyAttributes = new List<System.Xml.XmlAttribute>();
        }

        [XmlElement("import", Namespace = CmmnXml.Namespace)]
        public List<Import> Imports { get; set; }

        [XmlElement("caseFileItemDefinition", Namespace = CmmnXml.Namespace)]
        public List<CaseFileItemDefinition> CaseFileItemDefinitions { get; set; }

        [XmlElement("case", Namespace = CmmnXml.Namespace)]
        public List<Case> Cases { get; set; }

        [XmlElement("process", Namespace = CmmnXml.Namespace)]
        public List<Process> Processes { get; set; }

        [XmlElement("decision", Namespace = CmmnXml.Namespace)]
        public List<Decision> Decisions { get; set; }

        [XmlElement("extensionElements", Namespace = CmmnXml.Namespace)]
        public ExtensionElements ExtensionElements { get; set; }

        [XmlElement("relationship", Namespace = CmmnXml.Namespace)]
        public List<Relationship> Relationships { get; set; }

        [XmlElement("artifact", Type = typeof(Artifact), Namespace = CmmnXml.Namespace)]
        [XmlElement("association", Type = typeof(Association), Namespace = CmmnXml.Namespace)]
        [XmlElement("textAnnotation", Type = typeof(TextAnnotation), Namespace = CmmnXml.Namespace)]
        public List<Artifact> Artifacts { get; set; }

        [XmlIgnore]
        private readonly List<System.Xml.XmlAttribute> _anyAttributes;

        // tDefinitions' xsd:anyAttribute (##other, lax) - a get-only CONCRETE List (not
        // ICollection) precisely because of the XmlSerializer population behavior documented in
        // Model/CmmnXmlCollectionShadows.cs: hand-authored here, this type can simply use the
        // shape XmlSerializer populates, with no shadow/override indirection needed.
        // [JsonIgnore]/[IgnoreDataMember] for the same reason as the shadows: XmlAttribute is a
        // DOM node, not data System.Text.Json can round-trip.
        [JsonIgnore, IgnoreDataMember]
        [XmlAnyAttribute]
        public List<System.Xml.XmlAttribute> AnyAttributes => _anyAttributes;

        [XmlAttribute("id", DataType = "ID")]
        public string Id { get; set; }

        [XmlAttribute("name")]
        public string Name { get; set; }

        [XmlAttribute("targetNamespace", DataType = "anyURI")]
        public string TargetNamespace { get; set; }

        // Table 5.3: "The expression language used for this Definitions object. The default is
        // 'http://www.w3.org/1999/XPath.' This value MAY be overridden on each individual
        // Expression." Left null (not defaulted to the spec value) when the source XML omits it,
        // so import round-trips "the file didn't say" as null rather than manufacturing a value
        // the file never asserted - CmmnCapabilityLint treats an explicit non-Jint value here as a
        // document-level Degraded finding (see that class's remarks); this engine's own default,
        // regardless of what this attribute says, is always Wayfinder.Grains.Interfaces.Model.
        // ExpressionLanguage.Jint (SentryGrain.cs's D10 remarks / ExpressionGrain.BuildExecutable).
        [XmlAttribute("expressionLanguage", DataType = "anyURI")]
        public string ExpressionLanguage { get; set; }

        [XmlAttribute("exporter")]
        public string Exporter { get; set; }

        [XmlAttribute("exporterVersion")]
        public string ExporterVersion { get; set; }

        [XmlAttribute("author")]
        public string Author { get; set; }

        [XmlAttribute("creationDate")]
        public DateTime CreationDate { get; set; }

        // XmlSerializer convention (matches e.g. Association.DirectionSpecified in the generated
        // model): CreationDate is a non-nullable DateTime with no natural "absent" value, so this
        // sidecar - toggled automatically by XmlSerializer itself when (and only when) the source
        // XML actually carries a creationDate attribute - controls whether it round-trips as
        // "present" or "absent" on export.
        [XmlIgnore]
        public bool CreationDateSpecified { get; set; }
    }

    // tImport, transcribed from CMMN11.xsd verbatim: location is xsd:string (not anyURI),
    // namespace and importType are xsd:anyURI; location/importType are use="required" in the
    // schema but deliberately not enforced here - spec §9.1 requires implementers to accept
    // "incomplete" models by "disregarding missing attributes that are marked as 'required'".
    //
    // Structural only for this MVP (spec §9.3.1: "all definitions that are used in a file MUST be
    // imported directly or indirectly using the <cmmn:import> element"): this importer parses a
    // single file at a time and never dereferences an <import>'s namespace/location to load
    // another document, and QName-typed references elsewhere in the model
    // (CaseFileItem.DefinitionRef, ProcessTask.ProcessRef, ...) are round-tripped as opaque
    // values, never resolved - multi-file interchange is out of scope, and the engine's own
    // runtime does not consume these QNames either, only their string-IDREF counterparts within
    // a single file.
    [XmlType("tImport", Namespace = CmmnXml.Namespace)]
    [XmlRoot("import", Namespace = CmmnXml.Namespace)]
    public class Import
    {
        [XmlAttribute("namespace", DataType = "anyURI")]
        public string TargetNamespace { get; set; }

        [XmlAttribute("location")]
        public string Location { get; set; }

        [XmlAttribute("importType", DataType = "anyURI")]
        public string ImportType { get; set; }
    }
}
