<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
    <LangVersion>latest</LangVersion>
    <OutputType>Exe</OutputType>
    <StartupObject />
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="3.1.7" />
    <PackageReference Include="Microsoft.Orleans.EventSourcing" Version="3.2.2" />
    <PackageReference Include="Microsoft.Orleans.Hosting.AzureCloudServices" Version="3.2.2" />
    <PackageReference Include="Microsoft.Orleans.OrleansAzureUtils" Version="2.4.5" />
    <PackageReference Include="Microsoft.Orleans.Server" Version="3.2.2" />
    <PackageReference Include="Serilog.Exceptions" Version="5.6.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="3.0.1" />
    <PackageReference Include="Serilog.Sinks.Seq" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Flow.Grains.Interfaces\Flow.Grains.Interfaces.csproj" />
    <ProjectReference Include="..\Flow.Grains\Flow.Grains.csproj" />
  </ItemGroup>

</Project>
