using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Flow.Grains.Events;
using Flow.Grains.Expressions;
using Flow.Grains.Infrastructure.Extensions;
using Flow.Grains.Interfaces.Model;
using Flow.Grains.Plan.CaseFileItem;
using Flow.Grains.Plan.CmmnElement;
using Flow.Grains.Plan.Sentry.Events;
using Microsoft.Extensions.Logging;
using Orleans.Streams;

namespace Flow.Grains.Plan.Sentry
{
    /// <summary>
    /// A Sentry may consist of two parts:
    /// • Zero or more OnParts. An OnPart specifies the event that serves as trigger. When the event is catched, the OnPart is
    ///   said to “occur.”
    /// • Zero or one IfPart. The IfPart specifies a condition, as Expression that evaluates over the CaseFile. If all
    ///   OnParts of a Sentry have occurred and its IfPart (if existent) evaluates to TRUE, the Sentry is said to be
    ///   “satisfied.”
    ///
    /// A Sentry's OnPart is satisfied when one of the following conditions is satisfied:
    ///     • For a PlanItemOnPart, its Sentry referred by sentryRef has occurred.
    ///     • For a PlanItemOnPart or CaseFileItemOnPart, its sourceRef transitions into the transition described by the
    ///       standardEvent (PlanItemTransition, or CaseFileItemTransition).
    /// A Sentry is satisfied when one of the following conditions is satisfied:
    ///     • All of the OnParts are satisfied AND the IfPart condition evaluates to TRUE.
    ///     • All of the OnParts are satisfied AND there is no IfPart.
    ///     • The IfPart condition evaluates to TRUE AND there are no OnParts.
    ///
    /// Entry criterion sentries are considered ready for evaluation while the task, stage, or milestone is in Available state. Exit
    /// criterion sentries are considered ready for evaluation while the CasePlanModel, State, or Task is in Active state.
    /// Sentries are evaluated when events arrive to the system or when events are generated by the system. A single event may
    /// satisfy multiple sentries. Sentries with no OnPart must have an IfPart, and that IfPart will be evaluated for all
    /// CaseFileItem events because IfPart expressions are based on CaseFileItem properties.
    /// </summary>
    /// <remarks>
    /// D3 - "Sentries with no OnPart must have an IfPart, and that IfPart will be evaluated for all
    /// CaseFileItem events because IfPart expressions are based on CaseFileItem properties" (8.5,
    /// last sentence), and "The IfPart condition evaluates to TRUE AND there are no OnParts" (8.5's
    /// third satisfaction bullet). A standalone-IfPart Sentry (Definition.OnParts.Count == 0) has no
    /// per-item sourceRef to key a subscription on, so SubscribeToOnPartTransitions below
    /// additionally subscribes such a Sentry to a case-wide CaseFileItemTransitionedEvent stream
    /// (CaseFileItemAddress.CaseWideSentinel) that CaseFileItemGrain.PublishTransition now also
    /// publishes every transition to, regardless of which CaseFileItem changed - see
    /// HandleCaseWideCaseFileItemTransitioned. Topology choice (case-wide stream vs. enumerating
    /// every CaseFileItem id from the Case's caseFileModel and subscribing per-id): see
    /// CaseFileItemAddress.CaseWideSentinel's remarks - CaseFileItem instances are created ad-hoc,
    /// not from an enumerable model-driven definition graph (#16's design decision), so there is no
    /// fixed list to walk, and new items can appear at any point in a case's life.
    ///
    /// D5/D11 - a single Sentry instance is expected, by 8.5/8.6.4, to satisfy more than once over
    /// its life (see SentryStore's class remarks) - once per repetition of whatever an OnPart's
    /// source itself repeats as, or once per distinct relevant CaseFileItem event. HandleOnPartOccurred
    /// below distinguishes a genuinely new occurrence from a true at-least-once stream redelivery of
    /// the exact same transition via SentryStore.IsRedelivery (OccurrenceToken comparison), and
    /// Apply(OnPartNotRearmed) forgets exactly the one OnPart that just completed an AND-join whose
    /// IfPart evaluated FALSE - both superseding PR !18's single-OnPart-only, whole-sentry-clearing
    /// IfPartNotSatisfied.
    ///
    /// D10 (Bug #82, closed) - "its Sentry referred by sentryRef has occurred" (the first
    /// OnPart-satisfaction bullet above) describes a PlanItemOnPart whose exitCriterionRef names an
    /// ExitCriterion, occurring when THAT ExitCriterion's own Sentry is satisfied (Table 5.30: "the
    /// PlanItemOnPart of the Sentry occurs when the PlanItem referenced by sourceRef transits by
    /// the specified exitCriterion due to the Sentry that is refers being satisfied" / "When
    /// sentryRef is specified, standardEvent MUST have value 'exit.'"). HandlePlanItemTransitioned
    /// below matches x.ExitCriterionRef against @event.ExitCriterionRef for exactly this case - this
    /// was previously unreachable because PlanItemTransitionedEvent.ExitCriterionRef's one
    /// construction site (BaseBehavior.HandleTransitioned) never supplied a non-null value. Closed
    /// by threading "which ExitCriterion drove this Exit" from StageBehavior/TaskBehavior.
    /// HandleSentrySatisfied's ExitCriterion branch through to HandleTransitioned: Stateless's own
    /// parameterized-trigger mechanism (SetTriggerParameters&lt;string&gt;(PlanItemTransition.Exit)
    /// in PlanItemStateMachine's constructor, fired via the new IPlanItemStateMachine.
    /// FireAsync(PlanItemTransition, string) overload) carries the firing ExitCriterion's own Id as
    /// the Exit trigger's payload, which Stateless surfaces on the OnTransitionedAsync callback's
    /// Transition.Parameters - BaseBehavior.HandleTransitioned reads it from there and passes it
    /// into the PlanItemTransitionedEvent it publishes. MilestoneBehavior/EventListenerBehavior
    /// never fire Exit with a criterion (Milestones/EventListeners cannot have exitCriteriaRefs -
    /// 5.24), and CasePlanModelBehavior's own exit criterion fires Terminate, not Exit (ADO #66) -
    /// so only StageBehavior's/TaskBehavior's own-exit-criterion branches needed to change.
    /// CmmnCapabilityLint's former Rule 4 (PlanItemOnPart.ExitCriterionRef populated => Unsupported)
    /// is removed accordingly - see that class's remarks.
    ///
    /// D10 remainder - "ifPart errors swallowed without fault": closed. HandleOnPartOccurred and
    /// HandleCaseWideCaseFileItemTransitioned now raise Faulted/publish SentryFaultedEvent on an
    /// IfPart evaluation error, distinct from an evaluated-FALSE result (see IfPartResult). This was
    /// ALREADY only a partial deviation by the time this work item started: #17 (D1) made a missing
    /// IfPart.ContextRef fail closed (IfPart NOT satisfied, not a crash) - what remained, and is
    /// closed here, was the fault SIGNAL itself never being distinguished or surfaced.
    ///
    /// D10 remainder - "no expression-language dispatch": verified still open, NOT closed here.
    /// Expression.Language (5.4.7/Table 5.33) is read and stored on the model but Executable.cs
    /// (Flow.Grains/Executables/Executable.cs) always evaluates via Jint regardless of its value -
    /// no XPath/FEEL/JUEL dispatch exists. This capability lives entirely in ExpressionGrain/
    /// Executable/the Executables/ folder, not in SentryGrain/SentryStore - out of this work item's
    /// explicit scope (ExpressionGrain is consumed, never modified). Documented per this work item's
    /// brief ("If a row turns out to... belong to another item's scope, document that finding with
    /// evidence instead of forcing changes") rather than forced in.
    /// </remarks>
    public class SentryGrain :
        CmmnElementGrain<SentryStore, Interfaces.Model.Sentry>,
        ISentryGrain
    {
        public SentryGrain(ILogger<SentryGrain> logger) :
            base(logger)
        {
        }

        public override async Task OnActivateAsync(CancellationToken cancellationToken)
        {
            await base.OnActivateAsync(cancellationToken);

            if (TentativeState.Defined)
            {
                await SubscribeToOnPartTransitions(StreamFlags.Resume);
            }
        }

        public override async Task Define(string caseDefinitionId, Interfaces.Model.Sentry definition)
        {
            await base.Define(caseDefinitionId, definition);
            await SubscribeToOnPartTransitions(StreamFlags.Create);
        }

        // D3 - a Sentry with zero OnParts has nothing in Definition.OnParts to iterate, so it needs
        // its own subscription: the case-wide CaseFileItemTransitionedEvent stream (see this class's
        // remarks and CaseFileItemAddress.CaseWideSentinel). "Sentries with no OnPart must have an
        // IfPart" (8.5) - Definition.OnParts.Count == 0 without an IfPart is a malformed Sentry per
        // the spec's own MUST; subscribing case-wide only when an IfPart actually exists avoids
        // pointlessly subscribing (and later faulting on every CaseFileItem event) a Sentry that
        // cannot mean anything either way.
        private Task SubscribeToOnPartTransitions(StreamFlags flags) =>
            Task.WhenAll(
                Definition.OnParts.Count == 0 && Definition.IfPart != null
                    ? SubscribeTo<CaseFileItemTransitionedEvent>(
                        CaseFileItemAddress.CaseWideSentinel,
                        HandleCaseWideCaseFileItemTransitioned,
                        flags)
                    : Task.CompletedTask,
                Task.WhenAll(Definition.OnParts
                    .Select(onPart =>
                    {
                        switch (onPart)
                        {
                            case PlanItemOnPart planItemOnPart:
                            {
                                return SubscribeTo<PlanItemTransitionedEvent>(
                                    planItemOnPart.SourceRef,
                                    HandlePlanItemTransitioned,
                                    flags);
                            }
                            case CaseFileItemOnPart caseFileItemOnPart:
                            {
                                return SubscribeTo<CaseFileItemTransitionedEvent>(
                                    caseFileItemOnPart.SourceRef,
                                    HandleCaseFileItemTransitioned,
                                    flags);
                            }
                            default:
                            {
                                return Task.CompletedTask;
                            }
                        }
                    })));

        private async Task HandlePlanItemTransitioned(PlanItemTransitionedEvent @event, StreamSequenceToken token = null)
        {
            // ignore events that are not in this sentry's hierarchy
            if (!@event.SourceScope.StartsWith(_scope)) return;

            var onPart = Definition.PlanItemOnParts
                .SingleOrDefault(x =>
                    x.StandardEvent == @event.StandardEvent &&
                    (string.IsNullOrWhiteSpace(x.SourceRef) || x.SourceRef.Equals(@event.SourceDefinitionId) &&
                    (string.IsNullOrWhiteSpace(x.ExitCriterionRef) || x.ExitCriterionRef.Equals(@event.ExitCriterionRef))));

            // no matching onPart
            if (onPart == null) return;

            // D5 - see SentryStore's class remarks: SourceInstanceId is the specific PlanItem GRAIN
            // instance that transitioned, distinct per repetition (StageBehavior.CreateChild), and
            // is what lets a later, distinct repetition's occurrence be told apart from a redelivery
            // of the exact same transition.
            await HandleOnPartOccurred(onPart, @event.SourceScope, @event.SourceDefinitionId, @event.StandardEvent, @event.SourceInstanceId);
        }

        private async Task HandleCaseFileItemTransitioned(CaseFileItemTransitionedEvent @event, StreamSequenceToken token = null)
        {
            var onPart = Definition.CaseFileItemOnParts
                .SingleOrDefault(x =>
                    x.StandardEvent == @event.StandardEvent &&
                    (string.IsNullOrWhiteSpace(x.SourceRef) || x.SourceRef.Equals(@event.SourceDefinitionId)));

            // no matching onPart
            if (onPart == null) return;

            // D5 - a CaseFileItem has no per-instance concept to token against (one CaseFileItemGrain
            // persists for a given id across every operation - see CaseFileItemGrain); occurrences
            // fall back to SentryStore's null-token, latch-until-explicitly-cleared path.
            await HandleOnPartOccurred(onPart, @event.SourceScope, @event.SourceDefinitionId, @event.StandardEvent, occurrenceToken: null);
        }

        // D3 - a standalone-IfPart Sentry (no OnParts, per this class's remarks) has no AND-join to
        // complete: 8.5's third satisfaction bullet ("The IfPart condition evaluates to TRUE AND
        // there are no OnParts") makes satisfaction purely the IfPart's own truth value, re-evaluated
        // on every case-wide CaseFileItem event regardless of which item transitioned (8.5's last
        // sentence). Once Satisfied, further events are ignored - satisfaction is a one-time trigger
        // for whatever criterion references this Sentry (5.4.6: "A Sentry that is satisfied actually
        // triggers the PlanItem that refers to it"), the same as an OnPart-bearing Sentry never
        // un-satisfies once it has fired.
        private async Task HandleCaseWideCaseFileItemTransitioned(CaseFileItemTransitionedEvent @event, StreamSequenceToken token = null)
        {
            if (TentativeState.Satisfied) return;

            var ifPartResult = await EvaluateIfPart();

            if (ifPartResult.IsFaulted)
            {
                // D10 - see HandleOnPartOccurred's remarks for why a fault is distinguished from an
                // evaluated-FALSE IfPart. A standalone-IfPart Sentry has no OnPart to re-arm (there
                // are none), so only the fault signal itself is raised/published here.
                RaiseEvent(new Faulted());

                await ConfirmEvents();

                LogWithContext(logger => logger.LogWarning(
                    "{ElementType} {ElementScope}.{ElementId} | IfPart evaluation faulted: {ErrorMessage}",
                    Definition.GetType().Name,
                    _scope,
                    _instanceId,
                    ifPartResult.ErrorMessage));

                await PublishEvent(new SentryFaultedEvent(_scope, Definition.Id, ifPartResult.ErrorMessage));

                return;
            }

            if (!ifPartResult.Value) return;

            LogWithContext(logger => logger.LogInformation(
                "{ElementType} {ElementScope}.{ElementId} | standalone IfPart satisfied via case-wide CaseFileItem event {EventSourceScope}.{EventSourceId} transition {StandardEvent}",
                Definition.GetType().Name,
                _scope,
                _instanceId,
                @event.SourceScope,
                @event.SourceDefinitionId,
                @event.StandardEvent));

            RaiseEvent(new Satisfied());

            await ConfirmEvents();

            LogWithContext(logger => logger.LogInformation(
                "{ElementType} {ElementScope}.{ElementId} | sentry satisfied, notifying subscribers",
                Definition.GetType().Name,
                _scope,
                _instanceId));

            // 8.6.4: RepetitionRule re-spawning on a LATER satisfaction is gated on "an entry
            // criterion WITH an OnPart" specifically - a standalone-IfPart Sentry has none, so
            // OnPartOccurred is deliberately false here (not a placeholder): the OnPart-gated
            // repetition branches in StageBehavior/TaskBehavior/MilestoneBehavior.HandleSentrySatisfied
            // must not treat this satisfaction as OnPart-driven.
            await PublishEvent(new SentrySatisfiedEvent(_scope, Definition.Id, false));
        }

        private async Task HandleOnPartOccurred(OnPart onPart, string sourceScope, string sourceId, object standardEvent, string occurrenceToken)
        {
            // Idempotency guard: SentryStore.IsRedelivery distinguishes a true at-least-once stream
            // redelivery of the exact same logical transition (must be a no-op - see
            // HandlePlanItemTransitioned__Given_SameEventDeliveredTwice__Then_
            // PublishSentrySatisfiedEventExactlyOnce) from a genuinely new occurrence of this OnPart
            // (which per 8.5/8.6.4 MUST re-trigger the AND-join/IfPart check even if this Sentry was
            // already Satisfied by an earlier occurrence - see SentryStore's class remarks). This
            // replaces the prior blanket "TentativeState.Satisfied || already recorded" check, which
            // could never distinguish the two and so could never let this Sentry satisfy more than
            // once.
            if (TentativeState.IsRedelivery(onPart.Id, occurrenceToken))
            {
                return;
            }

            LogWithContext(logger => logger.LogInformation(
                "{ElementType} {ElementScope}.{ElementId} | {OnPartType} {OnPartId} occurred via {EventSourceScope}.{EventSourceId} transition {StandardEvent}",
                Definition.GetType().Name,
                _scope,
                _instanceId,
                onPart.GetType().Name,
                onPart.Id,
                sourceScope,
                sourceId,
                standardEvent));

            RaiseEvent(new OnPartOccurred
            {
                OnPart = onPart,
                OccurrenceToken = occurrenceToken
            });

            if (TentativeState.OccurredOnPartIds.Count() == Definition.OnParts.Count)
            {
                var ifPartResult = await EvaluateIfPart();

                if (ifPartResult.IsFaulted)
                {
                    // D10 - an IfPart expression that genuinely errors (as opposed to evaluating to
                    // FALSE) is not the same outcome as "not satisfied yet, try again later": FALSE
                    // means re-evaluate on the next relevant occurrence (handled below); a fault
                    // means the condition itself cannot be evaluated at all (e.g. its ContextRef
                    // names a CaseFileItem that was never created - see ExpressionGrain.
                    // BuildExecutable). Publishing a distinguishable fault event - rather than
                    // silently treating it as FALSE - lets an interested subscriber tell "will never
                    // fire without intervention" apart from "hasn't fired yet"; no such subscriber
                    // exists yet (out of this work item's scope per its brief - SentryGrain/
                    // SentryStore/its Events only), so this currently has no consumer, but the
                    // signal is no longer swallowed. Still re-arms this OnPart (same as the FALSE
                    // branch below) rather than latching the fault permanently: the underlying data
                    // problem (e.g. a not-yet-created ContextRef CaseFileItem) may resolve before
                    // the next relevant occurrence arrives, and there is no spec basis for treating
                    // a transient evaluation fault as more permanent than an evaluated-FALSE result.
                    RaiseEvent(new Faulted());
                    RaiseEvent(new OnPartNotRearmed
                    {
                        OnPartId = onPart.Id
                    });

                    await ConfirmEvents();

                    LogWithContext(logger => logger.LogWarning(
                        "{ElementType} {ElementScope}.{ElementId} | IfPart evaluation faulted: {ErrorMessage}",
                        Definition.GetType().Name,
                        _scope,
                        _instanceId,
                        ifPartResult.ErrorMessage));

                    await PublishEvent(new SentryFaultedEvent(_scope, Definition.Id, ifPartResult.ErrorMessage));

                    return;
                }

                if (ifPartResult.Value)
                {
                    RaiseEvent(new Satisfied());
                }
                else
                {
                    // D11 (generalizes PR !18's single-OnPart-only IfPartNotSatisfied) - 8.5: "a
                    // sentry whose OnParts have all occurred but whose IfPart is false does NOT
                    // fire... and must re-evaluate on subsequent relevant events." Forget only the
                    // OnPart that just completed this AND-join pass - not every recorded OnPart - so
                    // a later, distinct occurrence of THIS OnPart re-triggers the AND-join/IfPart
                    // check, while a sibling OnPart whose own source is inherently one-shot keeps its
                    // recorded occurrence and the AND-join stays reachable. See
                    // SentryStore.Apply(OnPartNotRearmed).
                    RaiseEvent(new OnPartNotRearmed
                    {
                        OnPartId = onPart.Id
                    });
                }
            }

            await ConfirmEvents();

            if (!State.Satisfied) return;

            LogWithContext(logger => logger.LogInformation(
                "{ElementType} {ElementScope}.{ElementId} | sentry satisfied, notifying subscribers",
                Definition.GetType().Name,
                _scope,
                _instanceId));

            await PublishEvent(new SentrySatisfiedEvent(_scope, Definition.Id, true));
        }

        private async Task<IfPartResult> EvaluateIfPart()
        {
            if (Definition.IfPart?.Condition == null) return IfPartResult.True;

            var result = await GrainFactory.GetGrain<IExpressionGrain>(_caseInstanceId)
                .ExecuteAsBool(Definition.IfPart.ContextRef, Definition.IfPart.Condition);

            return result.IsError
                ? IfPartResult.Fault(result.Message)
                : IfPartResult.Of(result.Value);
        }

        // D10 - distinguishes an IfPart that genuinely could not be evaluated (IsFaulted) from one
        // that evaluated cleanly to FALSE (Value == false, IsFaulted == false). Both currently cause
        // the sentry to not fire, but only the fault case raises Faulted/SentryFaultedEvent - see
        // HandleOnPartOccurred's remarks.
        private readonly struct IfPartResult
        {
            public static readonly IfPartResult True = new IfPartResult(true, false, null);

            public bool Value { get; }
            public bool IsFaulted { get; }
            public string ErrorMessage { get; }

            private IfPartResult(bool value, bool isFaulted, string errorMessage)
            {
                Value = value;
                IsFaulted = isFaulted;
                ErrorMessage = errorMessage;
            }

            public static IfPartResult Of(bool value) => new IfPartResult(value, false, null);
            public static IfPartResult Fault(string errorMessage) => new IfPartResult(false, true, errorMessage);
        }
    }
}
