using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Flow.Grains.Events;
using Flow.Grains.Expressions;
using Flow.Grains.Interfaces.Model;
using Flow.Grains.Plan.CmmnElement;
using Flow.Grains.Plan.Sentry.Events;
using Microsoft.Extensions.Logging;
using Orleans.Streams;

namespace Flow.Grains.Plan.Sentry
{
    /// <summary>
    /// A Sentry may consist of two parts:
    /// • Zero or more OnParts. An OnPart specifies the event that serves as trigger. When the event is catched, the OnPart is
    ///   said to “occur.”
    /// • Zero or one IfPart. The IfPart specifies a condition, as Expression that evaluates over the CaseFile. If all
    ///   OnParts of a Sentry have occurred and its IfPart (if existent) evaluates to TRUE, the Sentry is said to be
    ///   “satisfied.”
    /// 
    /// A Sentry's OnPart is satisfied when one of the following conditions is satisfied:
    ///     • For a PlanItemOnPart, its Sentry referred by sentryRef has occurred.
    ///     • For a PlanItemOnPart or CaseFileItemOnPart, its sourceRef transitions into the transition described by the
    ///       standardEvent (PlanItemTransition, or CaseFileItemTransition).
    /// A Sentry is satisfied when one of the following conditions is satisfied:
    ///     • All of the OnParts are satisfied AND the IfPart condition evaluates to TRUE.
    ///     • All of the OnParts are satisfied AND there is no IfPart.
    ///     • The IfPart condition evaluates to TRUE AND there are no OnParts.
    /// 
    /// Entry criterion sentries are considered ready for evaluation while the task, stage, or milestone is in Available state. Exit
    /// criterion sentries are considered ready for evaluation while the CasePlanModel, State, or Task is in Active state.
    /// Sentries are evaluated when events arrive to the system or when events are generated by the system. A single event may
    /// satisfy multiple sentries. Sentries with no OnPart must have an IfPart, and that IfPart will be evaluated for all
    /// CaseFileItem events because IfPart expressions are based on CaseFileItem properties.
    /// </summary>
    public class SentryGrain :
        CmmnElementGrain<SentryStore, Interfaces.Model.Sentry>,
        ISentryGrain
    {
        public SentryGrain(ILogger<SentryGrain> logger) :
            base(logger)
        {
        }

        public override async Task OnActivateAsync(CancellationToken cancellationToken)
        {
            await base.OnActivateAsync(cancellationToken);

            if (TentativeState.Defined)
            {
                await SubscribeToOnPartTransitions(StreamFlags.Resume);
            }
        }

        public override async Task Define(string caseDefinitionId, Interfaces.Model.Sentry definition)
        {
            await base.Define(caseDefinitionId, definition);
            await SubscribeToOnPartTransitions(StreamFlags.Create);
        }

        // DEVIATION/SIMPLIFICATION (out of scope for this work item, documented rather than silently
        // left unhandled): 8.5's last sentence - "Sentries with no OnPart must have an IfPart, and
        // that IfPart will be evaluated for all CaseFileItem events" - describes a standalone-IfPart
        // sentry (Definition.OnParts.Count == 0) that re-evaluates on every case-file event, not just
        // ones from a specific sourceRef. SubscribeToOnPartTransitions below only ever subscribes to
        // Definition.OnParts, so a 0-OnPart sentry subscribes to nothing and its IfPart is never
        // evaluated at all - EvaluateIfPart is unreachable for such a sentry today (it is only called
        // from HandleOnPartOccurred, which requires an OnPart to have fired first). This work item's
        // scope is IfPart evaluation *given* an OnPart occurrence (the flagship's
        // CaseFileItemOnPart + IfPart shape); wiring a 0-OnPart sentry to subscribe case-wide to every
        // CaseFileItemTransitionedEvent regardless of sourceRef is a materially different subscription
        // topology change and is left as a follow-on concern.
        private Task SubscribeToOnPartTransitions(StreamFlags flags) =>
            Task.WhenAll(Definition.OnParts
                .Select(onPart =>
                {
                    switch (onPart)
                    {
                        case PlanItemOnPart planItemOnPart:
                        {
                            return SubscribeTo<PlanItemTransitionedEvent>(
                                planItemOnPart.SourceRef,
                                HandlePlanItemTransitioned,
                                flags);
                        }
                        case CaseFileItemOnPart caseFileItemOnPart:
                        {
                            return SubscribeTo<CaseFileItemTransitionedEvent>(
                                caseFileItemOnPart.SourceRef,
                                HandleCaseFileItemTransitioned,
                                flags);
                        }
                        default:
                        {
                            return Task.CompletedTask;
                        }
                    }
                }));

        private async Task HandlePlanItemTransitioned(PlanItemTransitionedEvent @event, StreamSequenceToken token = null)
        {
            // ignore events that are not in this sentry's hierarchy
            if (!@event.SourceScope.StartsWith(_scope)) return;

            var onPart = Definition.PlanItemOnParts
                .SingleOrDefault(x =>
                    x.StandardEvent == @event.StandardEvent &&
                    (string.IsNullOrWhiteSpace(x.SourceRef) || x.SourceRef.Equals(@event.SourceDefinitionId) &&
                    (string.IsNullOrWhiteSpace(x.ExitCriterionRef) || x.ExitCriterionRef.Equals(@event.ExitCriterionRef))));

            // no matching onPart
            if (onPart == null) return;

            await HandleOnPartOccurred(onPart, @event.SourceScope, @event.SourceDefinitionId, @event.StandardEvent);
        }

        private async Task HandleCaseFileItemTransitioned(CaseFileItemTransitionedEvent @event, StreamSequenceToken token = null)
        {
            var onPart = Definition.CaseFileItemOnParts
                .SingleOrDefault(x =>
                    x.StandardEvent == @event.StandardEvent &&
                    (string.IsNullOrWhiteSpace(x.SourceRef) || x.SourceRef.Equals(@event.SourceDefinitionId)));

            // no matching onPart
            if (onPart == null) return;

            await HandleOnPartOccurred(onPart, @event.SourceScope, @event.SourceDefinitionId, @event.StandardEvent);
        }

        private async Task HandleOnPartOccurred(OnPart onPart, string sourceScope, string sourceId, object standardEvent)
        {
            // Idempotency guard against at-least-once redelivery of the same transition event:
            //   - a sentry that has already been satisfied has nothing further to do; re-running the
            //     satisfaction check and re-publishing SentrySatisfiedEvent would let a duplicate
            //     delivery drive a second (spurious) satisfaction downstream.
            //   - an OnPart that was already recorded as occurred (dovetails with the Id-based
            //     tracking in SentryStore) should not be re-raised/re-journaled; without this, a
            //     redelivered event that arrives after satisfaction was already reached elsewhere
            //     would still be a no-op count-wise, but would still perform a redundant raise and
            //     re-evaluate the IfPart unnecessarily.
            if (TentativeState.Satisfied || TentativeState.OccurredOnPartIds.Contains(onPart.Id))
            {
                return;
            }

            LogWithContext(logger => logger.LogInformation(
                "{ElementType} {ElementScope}.{ElementId} | {OnPartType} {OnPartId} occurred via {EventSourceScope}.{EventSourceId} transition {StandardEvent}",
                Definition.GetType().Name,
                _scope,
                _instanceId,
                onPart.GetType().Name,
                onPart.Id,
                sourceScope,
                sourceId,
                standardEvent));

            RaiseEvent(new OnPartOccurred
            {
                OnPart = onPart
            });

            if (TentativeState.OccurredOnPartIds.Count() == Definition.OnParts.Count)
            {
                if (await EvaluateIfPart())
                {
                    RaiseEvent(new Satisfied());
                }
                else if (Definition.OnParts.Count == 1)
                {
                    // 8.5: "a sentry whose OnParts have all occurred but whose IfPart is false does
                    // NOT fire... and must re-evaluate on subsequent relevant events." Forget the
                    // recorded occurrence so a later, distinct occurrence of this OnPart (e.g. a
                    // second CaseFileItemTransition.Update on the same CaseFileItem) re-triggers this
                    // AND-join/IfPart check, instead of being permanently swallowed by the redelivery
                    // guard above (see SentryStore.Apply(IfPartNotSatisfied)).
                    //
                    // DEVIATION/SIMPLIFICATION (documented per this work item's brief): scoped to
                    // single-OnPart sentries only. For 2+ OnParts, clearing every occurrence here
                    // would also forget an OnPart whose own source transition is inherently one-shot
                    // (e.g. a PlanItemTransition that only ever fires once in that plan item's
                    // lifecycle) - which would make the AND-join permanently unreachable rather than
                    // re-armed, the opposite of this fix's intent. The spec does not resolve which
                    // OnPart(s) should be "forgotten" versus which should stay recorded when only
                    // some of a multi-OnPart sentry's sources are repeatable, and no existing test
                    // exercises that combination; re-evaluation for multi-OnPart sentries gated by an
                    // IfPart is left as a follow-on concern rather than guessed at here.
                    RaiseEvent(new IfPartNotSatisfied());
                }
            }

            await ConfirmEvents();

            if (!State.Satisfied) return;

            LogWithContext(logger => logger.LogInformation(
                "{ElementType} {ElementScope}.{ElementId} | sentry satisfied, notifying subscribers",
                Definition.GetType().Name,
                _scope,
                _instanceId));

            await PublishEvent(new SentrySatisfiedEvent(_scope, Definition.Id, true));
        }
        
        private async Task<bool> EvaluateIfPart()
        {
            if (Definition.IfPart?.Condition == null) return true;

            var result = await GrainFactory.GetGrain<IExpressionGrain>(_caseInstanceId)
                .ExecuteAsBool(Definition.IfPart.ContextRef, Definition.IfPart.Condition);

            if (result.IsError) return false;

            // TODO: how do we handle a fault in a sentry?  publish event to fault the parent stage?

            return result.Value;
        }
    }
}
